export const stages = ["Full", "Onboarding", "Franchisee", "Prospect"] as const;

export const rows = [
  {
    id: 1,
    name: "Tech requirements.pdf",
    size: "220 KB",
    type: "Legal",
    ai: true,
    dashboard: true,
    stage: "Full",
  },
  {
    id: 2,
    name: "Dashboard screenshot.jpg",
    size: "720 KB",
    type: "Vendors & Assets",
    ai: true,
    dashboard: true,
    stage: "Onboarding",
  },
  {
    id: 3,
    name: "Dashboard prototype recording.mp4",
    size: "12 MB",
    type: "Technology",
    ai: true,
    dashboard: false,
    stage: "Franchisee",
  },
  {
    id: 4,
    name: "Financial Overview",
    size: "4.2 MB",
    type: "Financial",
    ai: false,
    dashboard: true,
    stage: "Prospect",
  },
  {
    id: 5,
    name: "UX Design Guidelines.docx",
    size: "400 KB",
    type: "Legal",
    ai: false,
    dashboard: false,
    stage: "Onboarding",
  },
  {
    id: 6,
    name: "Dashboard Interaction.aep",
    size: "12 MB",
    type: "Legal",
    ai: true,
    dashboard: true,
    stage: "Onboarding",
  },
  {
    id: 7,
    name: "Briefing call recording.mp3",
    size: "18.6 MB",
    type: "Financial",
    ai: false,
    dashboard: false,
    stage: "prospects",
  },
];
